name: snappitest_cicd

on:
  pull_request:
  release:
    types: [released]

jobs:
  snappitest_cicd:
    name: Run Snappi-tests after snappi-ixnetwork
    uses: open-traffic-generator/snappi-tests/.github/workflows/cicd.yml@Issue495-CI/CD
